<?php

declare(strict_types=1);

namespace LeKoala\Baresheet\Tests;

use LeKoala\Baresheet\CsvReader;
use LeKoala\Baresheet\Exception\InvalidDocumentException;
use LeKoala\Baresheet\HeaderSchema;
use LeKoala\Baresheet\OdsReader;
use LeKoala\Baresheet\OdsWriter;
use LeKoala\Baresheet\Options;
use LeKoala\Baresheet\XlsxReader;
use LeKoala\Baresheet\XlsxWriter;
use PHPUnit\Framework\TestCase;

class HeaderNormalizerTest extends TestCase
{
    private static function normalizeHeader(string $header): string
    {
        return strtolower(trim($header));
    }

    // ─── HeaderSchema ─────────────────────────────────────────

    public function testFromFlatHeadersAppliesNormalizer(): void
    {
        $schema = HeaderSchema::fromFlatHeaders(['  First Name ', 'Email  '], self::normalizeHeader(...));

        self::assertSame(['first name', 'email'], $schema->columnNames());
    }

    public function testFromHeadersAppliesNormalizer(): void
    {
        $schema = HeaderSchema::fromHeaders(['  First Name ', 'Email  '], 1, self::normalizeHeader(...));

        self::assertSame(['first name', 'email'], $schema->columnNames());
    }

    public function testFromRowsDoesNotNormalizeEmptyCells(): void
    {
        // The empty cell is the hierarchical "inherit parent" marker and must never reach the normalizer.
        $normalizer = static function (string $header): string {
            if ($header === '') {
                throw new \RuntimeException('normalizer must not be called on empty cells');
            }
            return strtolower($header);
        };

        $schema = HeaderSchema::fromRows([['Group', ''], ['A', 'B']], $normalizer);

        self::assertSame(['a', 'b'], $schema->columnNames());
    }

    public function testNormalizerCollisionsThrow(): void
    {
        $this->expectException(InvalidDocumentException::class);
        $this->expectExceptionMessage('Duplicate header');

        HeaderSchema::fromFlatHeaders(['Name', 'name'], self::normalizeHeader(...));
    }

    public function testDetectHeaderOffsetAppliesNormalizer(): void
    {
        $window = [['Title']];
        $queue = [
            [' First Name ', 'Email'],
            ['John',         'john@example.com'],
        ];
        $readNext = static function () use (&$queue) {
            return $queue === [] ? false : array_shift($queue);
        };

        $offset = HeaderSchema::detectHeaderOffset(
            ['first name'],
            1,
            $window,
            $readNext,
            50,
            self::normalizeHeader(...),
        );

        self::assertSame(1, $offset);
    }

    // ─── CSV end-to-end ───────────────────────────────────────

    public function testCsvNormalizerRunsBeforeSchemaColumnsAliases(): void
    {
        $csv = "\" First Name \",\" Email \",Age\nJohn,john@example.com,30\n";

        $reader = new CsvReader(new Options(
            assoc: true,
            headerNormalizer: self::normalizeHeader(...),
            requiredColumns: ['first name', 'email'],
            columns: ['email', 'first name'],
            aliases: ['email' => 'email_addr'],
        ));
        $data = iterator_to_array($reader->readString($csv));

        self::assertSame(
            ['email_addr' => 'john@example.com', 'first name' => 'John'],
            $data[0],
        );
    }

    public function testCsvNormalizerAppliesToInjectedHeaders(): void
    {
        $csv = "1,John,john@example.com\n";

        $reader = new CsvReader(new Options(
            assoc: true,
            headers: [' ID ', ' Name '],
            columns: ['name'],
            headerNormalizer: self::normalizeHeader(...),
        ));
        $data = iterator_to_array($reader->readString($csv));

        self::assertSame(['name' => 'John'], $data[0]);
    }

    public function testCsvAutoDetectUsesNormalizedRequiredColumns(): void
    {
        $csv = "Export clients\nGenerated by Foo\n\n\" First Name \",Email\nJohn,john@example.com\n";

        $reader = new CsvReader(new Options(
            assoc: true,
            headerOffset: 'auto',
            requiredColumns: ['first_name'],
            headerNormalizer: static fn(string $header): string => strtolower(str_replace(' ', '_', trim($header))),
        ));
        $data = iterator_to_array($reader->readString($csv));

        self::assertCount(1, $data);
        self::assertSame('John', $data[0]['first_name']);
        self::assertSame('john@example.com', $data[0]['email']);
    }

    // ─── XLSX / ODS end-to-end ─────────────────────────────────

    public function testXlsxNormalizerAppliesToReadHeaders(): void
    {
        $writer = new XlsxWriter();
        $output = $writer->writeString([
            [' First Name ', ' Email '],
            ['John',         'john@example.com'],
        ]);

        $reader = new XlsxReader(new Options(
            assoc: true,
            headerNormalizer: self::normalizeHeader(...),
        ));
        $data = iterator_to_array($reader->readString($output));

        self::assertSame('John', $data[0]['first name']);
        self::assertSame('john@example.com', $data[0]['email']);
    }

    public function testOdsNormalizerAppliesToReadHeaders(): void
    {
        $writer = new OdsWriter();
        $output = $writer->writeString([
            [' First Name ', ' Email '],
            ['John',         'john@example.com'],
        ]);

        $reader = new OdsReader(new Options(
            assoc: true,
            headerNormalizer: self::normalizeHeader(...),
        ));
        $data = iterator_to_array($reader->readString($output));

        self::assertSame('John', $data[0]['first name']);
        self::assertSame('john@example.com', $data[0]['email']);
    }
}
