<?php

declare(strict_types=1);

namespace LeKoala\Baresheet\Tests;

use LeKoala\Baresheet\CsvReader;
use LeKoala\Baresheet\Options;
use PHPUnit\Framework\TestCase;

class HeaderAutoDetectionTest extends TestCase
{
    public function testAutoDetectHeaderWithPreamble(): void
    {
        $csv = "Export clients - 2026\nGenerated by Foo\n\nFirst Name,Email\nJohn,john@example.com\n";

        $reader = new CsvReader(new Options(
            assoc: true,
            headerOffset: 'auto',
            requiredColumns: ['First Name', 'Email'],
        ));
        $data = iterator_to_array($reader->readString($csv));

        self::assertCount(1, $data);
        self::assertSame(
            [
                'First Name' => 'John',
                'Email' => 'john@example.com',
            ],
            $data[0],
        );
    }

    public function testAutoDetectHeaderWithCommentLikeLines(): void
    {
        $csv = "# Export from CRM\n# Date: 2026-07-25\n\nFirst Name,Email,Phone\nJohn,john@example.com,555\n";

        $reader = new CsvReader(new Options(
            assoc: true,
            headerOffset: 'auto',
            requiredColumns: ['First Name', 'Email'],
        ));
        $data = iterator_to_array($reader->readString($csv));

        self::assertCount(1, $data);
        self::assertSame('John', $data[0]['First Name']);
        self::assertSame('john@example.com', $data[0]['Email']);
    }

    public function testAutoDetectHeaderWithHierarchicalHeaders(): void
    {
        $csv = "Report Title\nGenerated 2026\n\nPerson,\nFirst Name,Email\nJohn,john@example.com\n";

        $reader = new CsvReader(new Options(
            assoc: true,
            headerRows: 2,
            headerOffset: 'auto',
            requiredColumns: ['Person' => ['First Name']],
        ));
        $data = iterator_to_array($reader->readString($csv));

        self::assertCount(1, $data);
        self::assertArrayHasKey('Person', $data[0]);
        self::assertSame('John', $data[0]['Person']['First Name']);
    }

    public function testAutoDetectRequiresRequiredColumns(): void
    {
        $csv = "Title\nName,Email\nJohn,john@example.com\n";

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('requires requiredColumns');

        $reader = new CsvReader(new Options(
            assoc: true,
            headerOffset: 'auto',
        ));
        iterator_to_array($reader->readString($csv));
    }

    public function testAutoDetectNotFound(): void
    {
        $csv = "Title\nOther\nName,Email\nJohn,john@example.com\n";

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Could not auto-detect');

        $reader = new CsvReader(new Options(
            assoc: true,
            headerOffset: 'auto',
            requiredColumns: ['Phone'], // Doesn't exist
        ));
        iterator_to_array($reader->readString($csv));
    }

    public function testExplicitHeaderOffsetStillWorks(): void
    {
        $csv = "Skip me\nAlso skip\nFirst Name,Email\nJohn,john@example.com\n";

        $reader = new CsvReader(new Options(
            assoc: true,
            headerOffset: 2,
        ));
        $data = iterator_to_array($reader->readString($csv));

        self::assertCount(1, $data);
        self::assertSame('John', $data[0]['First Name']);
    }
}
